name: Format code using prettier
on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Prettier
        run: npm install --global prettier
      - name: Check format
        run: npx prettier --check .
      - name: Format code
        if: failure()
        run: npx prettier --write .
      - name: Create pull request
        if: failure()
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: "style: Format code"
          title: "Format code for ${{ github.ref }}"
          branch: "auto-pr/format/${{ github.ref }}"
